services:
  postgres:
    image: postgres:16
    container_name: billing-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: billingdb
      POSTGRES_USER: billing_app
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  localstack:
    image: localstack/localstack:3.0.0
    container_name: billing-s3-mock
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs
      - DEFAULT_REGION=us-east-1
    volumes:
      - "./localstack_data:/var/lib/localstack"

  app:
    image: ghcr.io/jawadazeem/blueprint/billing-app:latest
    container_name: billing-app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
      aws-cli-setup:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/billingdb
      - SPRING_DATASOURCE_USERNAME=billing_app
      - SPRING_DATASOURCE_PASSWORD=875869
      - AWS_S3_ENDPOINT=http://localstack:4566
      - AWS_SQS_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY=test
      - AWS_SECRET_KEY=test

  aws-cli-setup:
    image: amazon/aws-cli
    container_name: infra-setup
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "
      echo 'Waiting for Localstack...';
      until curl -s http://billing-s3-mock:4566/_localstack/health | grep -q '\"s3\": \"running\"'; do sleep 2; done;
      
      echo 'Configuring SQS...';
      aws --endpoint-url=http://billing-s3-mock:4566 sqs create-queue --queue-name billing-event-queue;
      
      echo 'Configuring S3...';
      aws --endpoint-url=http://billing-s3-mock:4566 s3 mb s3://telecom-billing;
      
      echo 'Linking S3 to SQS (The Permanent Bridge)...';
      aws --endpoint-url=http://billing-s3-mock:4566 s3api put-bucket-notification-configuration --bucket telecom-billing --notification-configuration '{\"QueueConfigurations\":[{\"QueueArn\":\"arn:aws:sqs:us-east-1:000000000000:billing-event-queue\",\"Events\":[\"s3:ObjectCreated:*\"]}]}'
      
      echo 'Infrastructure configuration complete.'
      "

volumes:
  postgres_data: