# Configuration applied to all profiles (default)
spring:
  application:
    name: telecom-billing-processor
  cloud:
    aws:
      s3:
        endpoint: ${AWS_S3_ENDPOINT:http://billing-s3-mock:4566}
        path-style-access-enabled: true
      sqs:
        endpoint: ${AWS_SQS_ENDPOINT:http://billing-s3-mock:4566}
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY:test}
        secret-key: ${AWS_SECRET_KEY:test}
server:
  port: 8080
logging:
  file:
    name: app.log
# Business-specific configuration
alarm:
  department:
    monthlyLimit: 7500
  individual:
    low: 250
    medium: 370
    high: 500
  account:
    low: 45000
    high: 60000
billing-reader:
  has-header: true
  batch-size: 100

---
# Configuration for the 'dev' profile only
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      initialization-fail-timeout: 0
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: create-drop
---
# Configuration for the 'test' profile only
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: ${TEST_DB_URL}
    username: ${TEST_DB_USERNAME}
    password: ${TEST_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop

---
# Configuration for the 'prod' profile only
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update