# Configuration applied to all profiles (default)
spring:
  application:
    name: telecom-billing-processor
server:
  port: 8080
logging:
  file:
    name: app.log
alarm:
  department:
    monthlyLimit: 2500
  individual:
    low: 200
    medium: 350
    high: 500
  account:
    low: 15000
    high: 20000
billing-reader:
  has-header: true

---
# Configuration for the 'dev' profile only
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  billing:
    ingest:
      default-file: classpath:resources/azeemcom_telecom_usage_2025_01.csv
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
---
# Configuration for the 'test' profile only
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/billingdb
    username: billing_app
    password: 875869
  jpa:
    hibernate:
      ddl-auto: create-drop

---
# Configuration for the 'prod' profile only
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update